const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  // fetch các option gender từ all code
  FETCH_GENDER_START: "FETCH_GENDER_START",
  FETCH_GENDER_SUCCESS: "FETCH_GENDER_SUCCESS",
  FETCH_GENDER_FAILED: "FETCH_GENDER_FAILED",

  // fetch các option position từ all code
  FETCH_POSITION_START: "FETCH_POSITION_START",
  FETCH_POSITION_SUCCESS: "FETCH_POSITION_SUCCESS",
  FETCH_POSITION_FAILED: "FETCH_POSITION_FAILED",

  // fetch các option role từ all code
  FETCH_ROLE_START: "FETCH_ROLE_START",
  FETCH_ROLE_SUCCESS: "FETCH_ROLE_SUCCESS",
  FETCH_ROLE_FAILED: "FETCH_ROLE_FAILED",

  // create user
  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  // fetch all users
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",

  // edit user
  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  // delete users
  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  // fetch top doctor
  FETCH_TOP_DOCTOR_SUCCESS: "FETCH_TOP_DOCTOR_SUCCESS",
  FETCH_TOP_DOCTOR_FAILED: "FETCH_TOP_DOCTOR_FAILED",

  // fetch all doctor
  FETCH_ALL_DOCTOR_SUCCESS: "FETCH_ALL_DOCTOR_SUCCESS",
  FETCH_ALL_DOCTOR_FAILED: "FETCH_ALL_DOCTOR_FAILED",

  // fetch detail doctor by id
  FETCH_DETAIL_DOCTOR_BY_ID_SUCCESS: "FETCH_DETAIL_DOCTOR_BY_ID_SUCCESS",
  FETCH_DETAIL_DOCTOR_BY_ID_FAILED: "FETCH_DETAIL_DOCTOR_BY_ID_FAILED",

  // save detail cho doctor
  SAVE_DETAIL_DOCTOR_SUCCESS: "SAVE_DETAIL_DOCTOR_SUCCESS",
  SAVE_DETAIL_DOCTOR_FAILED: "SAVE_DETAIL_DOCTOR_FAILED",

  // Lấy thông tin Markdown để chỉnh sửa thông tin chi tiết của bác sĩ
  GET_MARKDOWN_DOCTOR_SUCCESS: "GET_MARKDOWN_DOCTOR_SUCCESS",
  GET_MARKDOWN_DOCTOR_FAILED: "GET_MARKDOWN_DOCTOR_FAILED",

  // Lấy giờ đặt lịch khám bệnh
  FETCH_SCHEDULE_TIMES_SUCCESS: "FETCH_SCHEDULE_TIMES_SUCCESS",
  FETCH_SCHEDULE_TIMES_FAILED: "FETCH_SCHEDULE_TIMES_FAILED",

  // Lấy thông tin Bác sĩ (giá,payment,tỉnh thành)
  FETCH_REQUIRED_DOCTOR_SUCCESS: "FETCH_REQUIRED_DOCTOR_SUCCESS",
  FETCH_REQUIRED_DOCTOR_FAILED: "FETCH_REQUIRED_DOCTOR_FAILED",

  // Lấy All thông tin về chuyên khoa
  FETCH_TOP_SPECIALTIES_SUCCESS: "FETCH_TOP_SPECIALTIES_SUCCESS",
  FETCH_TOP_SPECIALTIES_FAILED: "FETCH_TOP_SPECIALTIES_FAILED",

  // Lấy thông tin trong trang chi tiết chuyên khoa
  FETCH_DETAIL_SPECIALTY_BY_ID_SUCCESS: "FETCH_DETAIL_SPECIALTY_BY_ID_SUCCESS",
  FETCH_DETAIL_SPECIALTY_BY_ID_FAILED: "FETCH_DETAIL_SPECIALTY_BY_ID_FAILED",

  // Tạo mới 1 phòng khám
  CREATE_NEW_CLINIC_SUCCESS: "CREATE_NEW_CLINIC_SUCCESS",
  CREATE_NEW_CLINIC_FAILED: "CREATE_NEW_CLINIC_FAILED",

  // Hiển thị All phòng khám
  FETCH_ALL_CLINIC_SUCCESS: "FETCH_ALL_CLINIC_SUCCESS",
  FETCH_ALL_CLINIC_FAILED: "FETCH_ALL_CLINIC_FAILED",

  // Xóa phòng khám
  DELETE_CLINIC_SUCCESS: "DELETE_CLINIC_SUCCESS",
  DELETE_CLINIC_FAILED: "DELETE_CLINIC_FAILED",

  // Edit phòng khám
  EDIT_CLINIC_SUCCESS: "EDIT_CLINIC_SUCCESS",
  EDIT_CLINIC_FAILED: "EDIT_CLINIC_FAILED",

  // get all code province
  FETCH_PROVINCE_SUCCESS: "FETCH_PROVINCE_SUCCESS",
  FETCH_PROVINCE_FAILED: "FETCH_PROVINCE_FAILED",

  // Tạo mới 1 phòng khám
  CREATE_NEW_SPECIALTY_SUCCESS: "CREATE_NEW_SPECIALTY_SUCCESS",
  CREATE_NEW_SPECIALTY_FAILED: "CREATE_NEW_SPECIALTY_FAILED",

  // Hiển thị All phòng khám
  FETCH_ALL_SPECIALTY_SUCCESS: "FETCH_ALL_SPECIALTY_SUCCESS",
  FETCH_ALL_SPECIALTY_FAILED: "FETCH_ALL_SPECIALTY_FAILED",

  // Xóa phòng khám
  DELETE_SPECIALTY_SUCCESS: "DELETE_SPECIALTY_SUCCESS",
  DELETE_SPECIALTY_FAILED: "DELETE_SPECIALTY_FAILED",

  // Edit phòng khám
  EDIT_SPECIALTY_SUCCESS: "EDIT_SPECIALTY_SUCCESS",
  EDIT_SPECIALTY_FAILED: "EDIT_SPECIALTY_FAILED",

  // Hiển thị chi tiết phòng khám
  FETCH_DETAIL_CLINIC_BY_ID_SUCCESS: "FETCH_DETAIL_CLINIC_BY_ID_SUCCESS",
  FETCH_DETAIL_CLINIC_BY_ID_FAILED: "FETCH_DETAIL_CLINIC_BY_ID_FAILED",

  // list phòng khám theo tỉnh thành
  FETCH_LIST_CINIC_BY_PROVINCE_SUCCESS: "FETCH_LIST_CINIC_BY_PROVINCE_SUCCESS",
  FETCH_LIST_CINIC_BY_PROVINCE_FAILED: "FETCH_LIST_CINIC_BY_PROVINCE_FAILED",

  // list doctor theo tỉnh thành
  FETCH_LIST_DOCTOR_BY_PROVINCE_SUCCESS: "FETCH_LIST_DOCTOR_BY_PROVINCE_SUCCESS",
  FETCH_LIST_DOCTOR_BY_PROVINCE_FAILED: "FETCH_LIST_DOCTOR_BY_PROVINCE_FAILED",

  // Lấy danh sách lịch hẹn booking
  FETCH_LIST_PATIENT_FOR_DOCTOR_SUCCESS: "FETCH_LIST_PATIENT_FOR_DOCTOR_SUCCESS",
  FETCH_LIST_PATIENT_FOR_DOCTOR_FAILED: "FETCH_LIST_PATIENT_FOR_DOCTOR_FAILED",
  // Lấy danh sách lịch hẹn booking
  FETCH_LIST_BOOKING_DONE_SUCCESS: "FETCH_LIST_BOOKING_DONE_SUCCESS",
  FETCH_LIST_BOOKING_DONE_FAILED: "FETCH_LIST_BOOKING_DONE_FAILED",

  // Lấy user by id 
  FETCH_USER_BY_ID_SUCCESS: "FETCH_USER_BY_ID_SUCCESS",
  FETCH_USER_BY_ID_FAILED: "FETCH_USER_BY_ID_FAILED",
});


export default actionTypes;
